### ISSUE TITLE
[IDEA] Roadmap for Commander 3

### ISSUE THREAD

**Issue by kookma** [kookma/TW-Commander#37]
## Rewrite Commander in TiddlyWiki 5.3.6+

- [ ] Upgrade to use the new concepts in TW 5.3.0+ like procedures, functions, transclude
- [ ] Enhance the core code for readability and hackability
- [ ] Add more features for serach-and-replace using new features of TW 5.3.0+

## Make Commander UI more mobile friendly

- [ ]  Use grid layout

## Integrate with other plugins

- [ ] better integration with Relink
- [ ] integrate with Trashbin

I hope all interested users share idea/opinion here to have a powerful Commander 3.
